### ISSUE TITLE
'code' command not useful

### ISSUE THREAD

**Issue by lindseyberlin** [learn-co-curriculum/dsc-using-yelp-api-codealong#1]
We tell students to use the `code` command in their terminal to both create and open the `yelp_api.json` file - but that will only work if we have all students using VSCode as their text editor, which we never tell students to do. 

Instead it would be better to tell students to `touch yelp_api.json` to create the file, then simply ask them to open that file in the text editor of their choice

**Comment by Dmvinedata** [comment]
Thanks!  I searched the internet and found "touch" worked because "code" didn't.

**Comment by jilliankim** [comment]
handled the issue in this PR https://github.com/learn-co-curriculum/dsc-using-yelp-api-codealong/pull/4, closing the issue.
